In [4]:
# Importing relevant package
import pandas as pd
import numpy as np

In [5]:
# Bringing the dataset

df_static = pd.read_csv("/Users/abdullahhasib/Library/CloudStorage/OneDrive-SharedLibraries-NationalUniversityofSingapore/Ansel Lim - SPH6004_group/data/MIMIC-IV-static(Group Assignment).csv")
df_static

,subject_id,hadm_id,stay_id,first_careunit,last_careunit,icu_los_hours,intime,outtime,los,deathtime,...,ck_mb_max,ggt_min,ggt_max,ld_ldh_min,ld_ldh_max,so2_min,so2_max,po2_min,po2_max,radiology_note_count
0,12466550,23998182,30000153,Trauma SICU (TSICU),Trauma SICU (TSICU),39.286111,2174-09-29 12:09:00,2174-10-01 03:26:10,1.636921,NaN,...,3.3,NaN,NaN,NaN,NaN,NaN,NaN,215.0,263.0,5
1,13180007,27543152,30000213,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),39.246667,2162-06-21 05:38:00,2162-06-22 20:52:48,1.635278,NaN,...,NaN,NaN,NaN,300.0,300.0,NaN,NaN,56.0,63.0,1
2,18421337,22413411,30000484,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),59.493333,2136-01-14 17:23:32,2136-01-17 04:53:08,2.478889,NaN,...,NaN,NaN,NaN,419.0,419.0,NaN,NaN,21.0,21.0,5
3,12207593,22795209,30000646,Coronary Care Unit (CCU),Coronary Care Unit (CCU),112.740556,2194-04-29 01:39:22,2194-05-03 18:23:48,4.697523,2194-05-06 02:29:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71.0,71.0,5
4,12980335,23552849,30001148,Cardiac Vascular Intensive Care Unit (CVICU),Cardiac Vascular Intensive Care Unit (CVICU),27.243056,2156-08-30 11:10:59,2156-08-31 14:25:34,1.135127,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107.0,170.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76938,16180713,20178444,39999301,Cardiac Vascular Intensive Care Unit (CVICU),Cardiac Vascular Intensive Care Unit (CVICU),27.525833,2111-08-18 15:47:00,2111-08-19 19:18:33,1.146910,2111-08-19 15:00:00,...,NaN,NaN,NaN,175.0,175.0,NaN,NaN,68.0,320.0,1
76939,15498623,27161460,39999384,Surgical Intensive Care Unit (SICU),Surgical Intensive Care Unit (SICU),30.618333,2158-05-24 19:50:01,2158-05-26 02:27:07,1.275764,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
76940,11256534,26910235,39999552,Cardiac Vascular Intensive Care Unit (CVICU),Cardiac Vascular Intensive Care Unit (CVICU),28.022778,2186-07-17 14:27:43,2186-07-18 18:29:05,1.167616,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,137.0,343.0,2
76941,15403458,25335698,39999562,Neuro Intermediate,Neuro Intermediate,119.911111,2129-01-24 17:24:09,2129-01-29 17:18:49,4.996296,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
76942,17840864,22695803,39999810,Neuro Intermediate,Neuro Intermediate,113.849167,2115-12-01 00:37:00,2115-12-05 18:27:57,4.743715,NaN,...,NaN,NaN,NaN,105.0,248.0,NaN,NaN,NaN,NaN,1

In [6]:
# checking ICU types

first_careunit = df_static["first_careunit"].unique()
first_careunit

<StringArray>
[                             'Trauma SICU (TSICU)',
               'Medical Intensive Care Unit (MICU)',
                         'Coronary Care Unit (CCU)',
     'Cardiac Vascular Intensive Care Unit (CVICU)',
 'Medical/Surgical Intensive Care Unit (MICU/SICU)',
                               'Neuro Intermediate',
              'Surgical Intensive Care Unit (SICU)',
                                   'Neuro Stepdown',
  'Neuro Surgical Intensive Care Unit (Neuro SICU)']
Length: 9, dtype: str

In [7]:
### https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isin.html
#dropping non ICU units

EXCLUDED_CAREUNITS = ["Neuro Intermediate", "Neuro Stepdown"]
df_INCLUDED_ICU = df_static[~df_static["first_careunit"].isin(EXCLUDED_CAREUNITS)]
df_INCLUDED_ICU

,subject_id,hadm_id,stay_id,first_careunit,last_careunit,icu_los_hours,intime,outtime,los,deathtime,...,ck_mb_max,ggt_min,ggt_max,ld_ldh_min,ld_ldh_max,so2_min,so2_max,po2_min,po2_max,radiology_note_count
0,12466550,23998182,30000153,Trauma SICU (TSICU),Trauma SICU (TSICU),39.286111,2174-09-29 12:09:00,2174-10-01 03:26:10,1.636921,NaN,...,3.3,NaN,NaN,NaN,NaN,NaN,NaN,215.0,263.0,5
1,13180007,27543152,30000213,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),39.246667,2162-06-21 05:38:00,2162-06-22 20:52:48,1.635278,NaN,...,NaN,NaN,NaN,300.0,300.0,NaN,NaN,56.0,63.0,1
2,18421337,22413411,30000484,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),59.493333,2136-01-14 17:23:32,2136-01-17 04:53:08,2.478889,NaN,...,NaN,NaN,NaN,419.0,419.0,NaN,NaN,21.0,21.0,5
3,12207593,22795209,30000646,Coronary Care Unit (CCU),Coronary Care Unit (CCU),112.740556,2194-04-29 01:39:22,2194-05-03 18:23:48,4.697523,2194-05-06 02:29:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71.0,71.0,5
4,12980335,23552849,30001148,Cardiac Vascular Intensive Care Unit (CVICU),Cardiac Vascular Intensive Care Unit (CVICU),27.243056,2156-08-30 11:10:59,2156-08-31 14:25:34,1.135127,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107.0,170.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76936,13651601,22584645,39999230,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),211.378333,2147-08-31 22:31:28,2147-09-09 17:54:10,8.807431,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.0,98.0,12
76937,11305179,22341980,39999286,Surgical Intensive Care Unit (SICU),Surgical Intensive Care Unit (SICU),27.780000,2158-03-07 11:15:18,2158-03-08 15:02:06,1.157500,NaN,...,NaN,NaN,NaN,195.0,195.0,NaN,NaN,NaN,NaN,1
76938,16180713,20178444,39999301,Cardiac Vascular Intensive Care Unit (CVICU),Cardiac Vascular Intensive Care Unit (CVICU),27.525833,2111-08-18 15:47:00,2111-08-19 19:18:33,1.146910,2111-08-19 15:00:00,...,NaN,NaN,NaN,175.0,175.0,NaN,NaN,68.0,320.0,1
76939,15498623,27161460,39999384,Surgical Intensive Care Unit (SICU),Surgical Intensive Care Unit (SICU),30.618333,2158-05-24 19:50:01,2158-05-26 02:27:07,1.275764,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
76940,11256534,26910235,39999552,Cardiac Vascular Intensive Care Unit (CVICU),Cardiac Vascular Intensive Care Unit (CVICU),28.022778,2186-07-17 14:27:43,2186-07-18 18:29:05,1.167616,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,137.0,343.0,2

In [20]:
#converting intime to datetime format so that we can sort time-based operations on it later on
df_INCLUDED_ICU["intime"].dtype

dtype('<M8[us]')

In [21]:
#checking the format of the "intime" column 
df_INCLUDED_ICU["intime"] = pd.to_datetime(df_INCLUDED_ICU["intime"])
df_INCLUDED_ICU["intime"].dtype

dtype('<M8[us]')

In [22]:
# we only intend to consider the first ICU stay of each patient so we sorting the dataframe by "intime" in ascending order to make sure the first arrival is on top
df_intime = df_INCLUDED_ICU.sort_values("intime")

df_intime.head()

,subject_id,hadm_id,stay_id,first_careunit,last_careunit,icu_los_hours,intime,outtime,los,deathtime,...,ck_mb_max,ggt_min,ggt_max,ld_ldh_min,ld_ldh_max,so2_min,so2_max,po2_min,po2_max,radiology_note_count
4638,18106347,24305596,30588857,Cardiac Vascular Intensive Care Unit (CVICU),Cardiac Vascular Intensive Care Unit (CVICU),31.028056,2110-01-11 10:16:06,2110-01-12 17:17:47,1.292836,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,140.0,276.0,2
64093,17195991,23542772,38319097,Surgical Intensive Care Unit (SICU),Surgical Intensive Care Unit (SICU),69.227500,2110-01-12 00:54:00,2110-01-14 22:07:39,2.884479,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.0,48.0,4
52478,16284044,23864737,36817845,Cardiac Vascular Intensive Care Unit (CVICU),Cardiac Vascular Intensive Care Unit (CVICU),60.598056,2110-01-13 09:09:40,2110-01-15 21:45:33,2.524919,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,129.0,353.0,3
75031,18122666,23883987,39753527,Medical/Surgical Intensive Care Unit (MICU/SICU),Medical/Surgical Intensive Care Unit (MICU/SICU),29.776667,2110-01-14 07:22:00,2110-01-15 13:08:36,1.240694,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
16468,18780420,28977824,32140208,Neuro Surgical Intensive Care Unit (Neuro SICU),Neuro Surgical Intensive Care Unit (Neuro SICU),24.889444,2110-01-17 00:28:00,2110-01-18 01:21:22,1.037060,NaN,...,NaN,NaN,NaN,86.0,86.0,NaN,NaN,NaN,NaN,2

In [23]:
### https://www.youtube.com/watch?v=txMdrV1Ut64
# after that we group the dataframe by "subject_id" and bring them to the first row of each group
df_intime_new = df_intime.groupby("subject_id").first().reset_index()

df_intime_new.head()

/var/folders/gs/w9gkn6md2jj51cc9mwcqwpnr0000gn/T/ipykernel_11981/2495107388.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_intime_new = df_intime.groupby("subject_id").first().reset_index()

,subject_id,hadm_id,stay_id,first_careunit,last_careunit,icu_los_hours,intime,outtime,los,deathtime,...,ck_mb_max,ggt_min,ggt_max,ld_ldh_min,ld_ldh_max,so2_min,so2_max,po2_min,po2_max,radiology_note_count
0,10000032,29079034,39553978,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),9.846389,2180-07-23 14:00:00,2180-07-23 23:50:47,0.410266,NaN,...,NaN,NaN,NaN,173.0,173.0,NaN,NaN,NaN,NaN,1
1,10000980,26913865,39765666,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),11.940833,2189-06-27 08:42:00,2189-06-27 20:38:27,0.497535,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,10001217,24597018,37067082,Surgical Intensive Care Unit (SICU),Surgical Intensive Care Unit (SICU),26.832778,2157-11-20 19:18:02,2157-11-21 22:08:00,1.118032,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
3,10001725,25563031,31205490,Medical/Surgical Intensive Care Unit (MICU/SICU),Medical/Surgical Intensive Care Unit (MICU/SICU),32.126111,2110-04-11 15:52:22,2110-04-12 23:59:56,1.338588,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
4,10001884,26184834,37510196,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),220.123611,2131-01-11 04:20:05,2131-01-20 08:27:30,9.171817,2131-01-20 05:15:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,49.0,11

In [ ]:
# checking result - the number of subject_id should be the same as the length of the new dataframe as we collapsed them
print(f"Unique patients: {df_intime_new['subject_id'].nunique()}")
print(f"Total rows: {len(df_intime_new)}")

Unique patients: 51333
Total rows: 51333

In [28]:
# checking the value of icu_los_hours 
df_intime_new["icu_los_hours"]

0          9.846389
1         11.940833
2         26.832778
3         32.126111
4        220.123611
            ...
51328    166.808889
51329     23.057778
51330     42.983889
51331    127.146389
51332     46.508333
Name: icu_los_hours, Length: 51333, dtype: float64

In [54]:
#include only icu_los_hours which corresponds the value of more than 24 hours
df_cohort = df_intime_new[df_intime_new["icu_los_hours"] > 24]

df_cohort

,subject_id,hadm_id,stay_id,first_careunit,last_careunit,icu_los_hours,intime,outtime,los,deathtime,...,ck_mb_max,ggt_min,ggt_max,ld_ldh_min,ld_ldh_max,so2_min,so2_max,po2_min,po2_max,radiology_note_count
2,10001217,24597018,37067082,Surgical Intensive Care Unit (SICU),Surgical Intensive Care Unit (SICU),26.832778,2157-11-20 19:18:02,2157-11-21 22:08:00,1.118032,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
3,10001725,25563031,31205490,Medical/Surgical Intensive Care Unit (MICU/SICU),Medical/Surgical Intensive Care Unit (MICU/SICU),32.126111,2110-04-11 15:52:22,2110-04-12 23:59:56,1.338588,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
4,10001884,26184834,37510196,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),220.123611,2131-01-11 04:20:05,2131-01-20 08:27:30,9.171817,2131-01-20 05:15:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,49.0,11
5,10002013,23581541,39060235,Cardiac Vascular Intensive Care Unit (CVICU),Cardiac Vascular Intensive Care Unit (CVICU),31.544444,2160-05-18 10:00:53,2160-05-19 17:33:33,1.314352,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.0,462.0,1
6,10002155,23822395,33685454,Coronary Care Unit (CCU),Coronary Care Unit (CCU),148.293889,2129-08-04 12:45:00,2129-08-10 17:02:38,6.178912,2131-03-10 21:53:00,...,18.2,NaN,NaN,507.0,507.0,NaN,NaN,76.0,76.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51327,19999297,21439025,37364566,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),168.569167,2162-08-16 05:48:32,2162-08-23 06:22:41,7.023715,2162-08-23 04:16:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
51328,19999442,26785317,32336619,Surgical Intensive Care Unit (SICU),Surgical Intensive Care Unit (SICU),166.808889,2148-11-19 14:23:43,2148-11-26 13:12:15,6.950370,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,131.0,209.0,6
51330,19999828,25744818,36075953,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),42.983889,2149-01-08 18:12:00,2149-01-10 13:11:02,1.790995,NaN,...,NaN,NaN,NaN,238.0,238.0,NaN,NaN,35.0,36.0,1
51331,19999840,21033226,38978960,Trauma SICU (TSICU),Surgical Intensive Care Unit (SICU),127.146389,2164-09-12 09:26:28,2164-09-17 16:35:15,5.297766,2164-09-17 13:42:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61.0,212.0,8
51332,19999987,23865745,36195440,Trauma SICU (TSICU),Trauma SICU (TSICU),46.508333,2145-11-02 22:59:00,2145-11-04 21:29:30,1.937847,NaN,...,11.2,NaN,NaN,100.0,100.0,NaN,NaN,114.0,114.0,3

In [55]:
### https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf
#making sure the minimum value of icu_los_hours is more than 24 hours
df_cohort['icu_los_hours'].min()

np.float64(24.00111111111111)

In [ ]:
#same like before but we do it now for dead patients
#some patients maybe dead before 24 hours in icu but discharge after hour 24, e.g. die at hour 20 but discharge at hour 30

#checking the format of deathtime column
df_cohort["deathtime"].dtype

In [57]:
#converting deathtime to datetime format
df_cohort["deathtime"] = pd.to_datetime(df_cohort["deathtime"])

print(df_cohort["deathtime"].dtype)

datetime64[us]

In [58]:
#copnverting to hours with 3600 and adding a new column "hours_to_death" to the dataframe
df_cohort["hours_to_death"] = (
    df_cohort["deathtime"] - df_cohort["intime"]
).dt.total_seconds() / 3600

/var/folders/gs/w9gkn6md2jj51cc9mwcqwpnr0000gn/T/ipykernel_11981/756122157.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_cohort["hours_to_death"] = (

In [76]:
df_cohort["hours_to_death"]

2                 NaN
3                 NaN
4          216.915278
5                 NaN
6        14001.133333
             ...
51327      166.457778
51328             NaN
51330             NaN
51331      124.258889
51332             NaN
Name: hours_to_death, Length: 40457, dtype: float64

In [77]:
#inclding only patietns who died after 24 hours in ICU
died_before_24 = df_cohort["hours_to_death"] < 24

died_before_24.unique()

array([False])

In [ ]:
#make it back into the dataframe
df_cohort = df_cohort[~died_before_24]
df_cohort

,subject_id,hadm_id,stay_id,first_careunit,last_careunit,icu_los_hours,intime,outtime,los,deathtime,...,ggt_min,ggt_max,ld_ldh_min,ld_ldh_max,so2_min,so2_max,po2_min,po2_max,radiology_note_count,hours_to_death
2,10001217,24597018,37067082,Surgical Intensive Care Unit (SICU),Surgical Intensive Care Unit (SICU),26.832778,2157-11-20 19:18:02,2157-11-21 22:08:00,1.118032,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
3,10001725,25563031,31205490,Medical/Surgical Intensive Care Unit (MICU/SICU),Medical/Surgical Intensive Care Unit (MICU/SICU),32.126111,2110-04-11 15:52:22,2110-04-12 23:59:56,1.338588,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
4,10001884,26184834,37510196,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),220.123611,2131-01-11 04:20:05,2131-01-20 08:27:30,9.171817,2131-01-20 05:15:00,...,NaN,NaN,NaN,NaN,NaN,NaN,40.0,49.0,11,216.915278
5,10002013,23581541,39060235,Cardiac Vascular Intensive Care Unit (CVICU),Cardiac Vascular Intensive Care Unit (CVICU),31.544444,2160-05-18 10:00:53,2160-05-19 17:33:33,1.314352,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,90.0,462.0,1,NaN
6,10002155,23822395,33685454,Coronary Care Unit (CCU),Coronary Care Unit (CCU),148.293889,2129-08-04 12:45:00,2129-08-10 17:02:38,6.178912,2131-03-10 21:53:00,...,NaN,NaN,507.0,507.0,NaN,NaN,76.0,76.0,4,14001.133333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51327,19999297,21439025,37364566,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),168.569167,2162-08-16 05:48:32,2162-08-23 06:22:41,7.023715,2162-08-23 04:16:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,166.457778
51328,19999442,26785317,32336619,Surgical Intensive Care Unit (SICU),Surgical Intensive Care Unit (SICU),166.808889,2148-11-19 14:23:43,2148-11-26 13:12:15,6.950370,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,131.0,209.0,6,NaN
51330,19999828,25744818,36075953,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),42.983889,2149-01-08 18:12:00,2149-01-10 13:11:02,1.790995,NaT,...,NaN,NaN,238.0,238.0,NaN,NaN,35.0,36.0,1,NaN
51331,19999840,21033226,38978960,Trauma SICU (TSICU),Surgical Intensive Care Unit (SICU),127.146389,2164-09-12 09:26:28,2164-09-17 16:35:15,5.297766,2164-09-17 13:42:00,...,NaN,NaN,NaN,NaN,NaN,NaN,61.0,212.0,8,124.258889
51332,19999987,23865745,36195440,Trauma SICU (TSICU),Trauma SICU (TSICU),46.508333,2145-11-02 22:59:00,2145-11-04 21:29:30,1.937847,NaT,...,NaN,NaN,100.0,100.0,NaN,NaN,114.0,114.0,3,NaN

In [ ]:
### https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html
# exporting to working directory

df_cohort.to_csv("cohort.csv", index=False)