In [1]:
import pandas as pd

In [2]:
df_cohort_step3 = pd.read_csv("cohort_step_2.csv")

df_cohort_step3.head()

,subject_id,hadm_id,stay_id,first_careunit,last_careunit,icu_los_hours,intime,outtime,los,deathtime,...,ld_ldh_min,ld_ldh_max,so2_min,so2_max,po2_min,po2_max,radiology_note_count,hours_to_death,label_Y48,label_Y72
0,10001217,24597018,37067082,Surgical Intensive Care Unit (SICU),Surgical Intensive Care Unit (SICU),26.832778,2157-11-20 19:18:02,2157-11-21 22:08:00,1.118032,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,1,1
1,10001725,25563031,31205490,Medical/Surgical Intensive Care Unit (MICU/SICU),Medical/Surgical Intensive Care Unit (MICU/SICU),32.126111,2110-04-11 15:52:22,2110-04-12 23:59:56,1.338588,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,1,1
2,10001884,26184834,37510196,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),220.123611,2131-01-11 04:20:05,2131-01-20 08:27:30,9.171817,2131-01-20 05:15:00,...,NaN,NaN,NaN,NaN,40.0,49.0,11,216.915278,0,0
3,10002013,23581541,39060235,Cardiac Vascular Intensive Care Unit (CVICU),Cardiac Vascular Intensive Care Unit (CVICU),31.544444,2160-05-18 10:00:53,2160-05-19 17:33:33,1.314352,NaN,...,NaN,NaN,NaN,NaN,90.0,462.0,1,NaN,1,1
4,10002155,23822395,33685454,Coronary Care Unit (CCU),Coronary Care Unit (CCU),148.293889,2129-08-04 12:45:00,2129-08-10 17:02:38,6.178912,2131-03-10 21:53:00,...,507.0,507.0,NaN,NaN,76.0,76.0,4,14001.133333,0,0

In [3]:
# checking all available columns

df_cohort_step3.columns.tolist()

['subject_id',
 'hadm_id',
 'stay_id',
 'first_careunit',
 'last_careunit',
 'icu_los_hours',
 'intime',
 'outtime',
 'los',
 'deathtime',
 'icu_death_flag',
 'insurance',
 'language',
 'race',
 'marital_status',
 'hospital_expire_flag',
 'age',
 'gender',
 'sofa2_respiration_24h_max',
 'sofa2_cardiovascular_24h_max',
 'sofa2_coagulation_24h_max',
 'sofa2_liver_24h_max',
 'sofa2_renal_24h_max',
 'sofa2_cns_24h_max',
 'heart_rate_min',
 'heart_rate_max',
 'heart_rate_mean',
 'sbp_min',
 'sbp_max',
 'sbp_mean',
 'dbp_min',
 'dbp_max',
 'dbp_mean',
 'mbp_min',
 'mbp_max',
 'mbp_mean',
 'resp_rate_min',
 'resp_rate_max',
 'resp_rate_mean',
 'temperature_min',
 'temperature_max',
 'temperature_mean',
 'spo2_min',
 'spo2_max',
 'spo2_mean',
 'glucose_min',
 'glucose_max',
 'glucose_mean',
 'gcs_min',
 'gcs_motor',
 'gcs_verbal',
 'gcs_eyes',
 'gcs_unable',
 'hematocrit_min',
 'hematocrit_max',
 'hemoglobin_min',
 'hemoglobin_max',
 'platelets_min',
 'platelets_max',
 'wbc_min',
 'wbc_max',
 'albumin_min',
 'albumin_max',
 'globulin_min',
 'globulin_max',
 'total_protein_min',
 'total_protein_max',
 'aniongap_min',
 'aniongap_max',
 'bicarbonate_min',
 'bicarbonate_max',
 'bun_min',
 'bun_max',
 'calcium_min',
 'calcium_max',
 'chloride_min',
 'chloride_max',
 'creatinine_min',
 'creatinine_max',
 'sodium_min',
 'sodium_max',
 'potassium_min',
 'potassium_max',
 'abs_basophils_min',
 'abs_basophils_max',
 'abs_eosinophils_min',
 'abs_eosinophils_max',
 'abs_lymphocytes_min',
 'abs_lymphocytes_max',
 'abs_monocytes_min',
 'abs_monocytes_max',
 'abs_neutrophils_min',
 'abs_neutrophils_max',
 'atyps_min',
 'atyps_max',
 'bands_min',
 'bands_max',
 'imm_granulocytes_min',
 'imm_granulocytes_max',
 'metas_min',
 'metas_max',
 'nrbc_min',
 'nrbc_max',
 'd_dimer_min',
 'd_dimer_max',
 'fibrinogen_min',
 'fibrinogen_max',
 'thrombin_min',
 'thrombin_max',
 'inr_min',
 'inr_max',
 'pt_min',
 'pt_max',
 'ptt_min',
 'ptt_max',
 'alt_min',
 'alt_max',
 'alp_min',
 'alp_max',
 'ast_min',
 'ast_max',
 'amylase_min',
 'amylase_max',
 'bilirubin_total_min',
 'bilirubin_total_max',
 'bilirubin_direct_min',
 'bilirubin_direct_max',
 'bilirubin_indirect_min',
 'bilirubin_indirect_max',
 'ck_cpk_min',
 'ck_cpk_max',
 'ck_mb_min',
 'ck_mb_max',
 'ggt_min',
 'ggt_max',
 'ld_ldh_min',
 'ld_ldh_max',
 'so2_min',
 'so2_max',
 'po2_min',
 'po2_max',
 'radiology_note_count',
 'hours_to_death',
 'label_Y48',
 'label_Y72']

In [4]:
Identifier = ['subject_id',
 'hadm_id',
 'stay_id',
 'last_careunit',
 'icu_los_hours',
 'outtime',
 'los',
 'deathtime',
 'icu_death_flag',
 'hospital_expire_flag',
 'hours_to_death']

Demographics = ['insurance',
 'language',
 'race',
 'marital_status',
 'age',
 'gender',
 'first_careunit']

label = ['label_Y48', 'label_Y72']

static_features = ['sofa2_respiration_24h_max',
 'sofa2_cardiovascular_24h_max',
 'sofa2_coagulation_24h_max',
 'sofa2_liver_24h_max',
 'sofa2_renal_24h_max',
 'sofa2_cns_24h_max',
 'heart_rate_min',
 'heart_rate_max',
 'heart_rate_mean',
 'sbp_min',
 'sbp_max',
 'sbp_mean',
 'dbp_min',
 'dbp_max',
 'dbp_mean',
 'mbp_min',
 'mbp_max',
 'mbp_mean',
 'resp_rate_min',
 'resp_rate_max',
 'resp_rate_mean',
 'temperature_min',
 'temperature_max',
 'temperature_mean',
 'spo2_min',
 'spo2_max',
 'spo2_mean',
 'glucose_min',
 'glucose_max',
 'glucose_mean',
 'gcs_min',
 'gcs_motor',
 'gcs_verbal',
 'gcs_eyes',
 'gcs_unable',
 'hematocrit_min',
 'hematocrit_max',
 'hemoglobin_min',
 'hemoglobin_max',
 'platelets_min',
 'platelets_max',
 'wbc_min',
 'wbc_max',
 'albumin_min',
 'albumin_max',
 'globulin_min',
 'globulin_max',
 'total_protein_min',
 'total_protein_max',
 'aniongap_min',
 'aniongap_max',
 'bicarbonate_min',
 'bicarbonate_max',
 'bun_min',
 'bun_max',
 'calcium_min',
 'calcium_max',
 'chloride_min',
 'chloride_max',
 'creatinine_min',
 'creatinine_max',
 'sodium_min',
 'sodium_max',
 'potassium_min',
 'potassium_max',
 'abs_basophils_min',
 'abs_basophils_max',
 'abs_eosinophils_min',
 'abs_eosinophils_max',
 'abs_lymphocytes_min',
 'abs_lymphocytes_max',
 'abs_monocytes_min',
 'abs_monocytes_max',
 'abs_neutrophils_min',
 'abs_neutrophils_max',
 'atyps_min',
 'atyps_max',
 'bands_min',
 'bands_max',
 'imm_granulocytes_min',
 'imm_granulocytes_max',
 'metas_min',
 'metas_max',
 'nrbc_min',
 'nrbc_max',
 'd_dimer_min',
 'd_dimer_max',
 'fibrinogen_min',
 'fibrinogen_max',
 'thrombin_min',
 'thrombin_max',
 'inr_min',
 'inr_max',
 'pt_min',
 'pt_max',
 'ptt_min',
 'ptt_max',
 'alt_min',
 'alt_max',
 'alp_min',
 'alp_max',
 'ast_min',
 'ast_max',
 'amylase_min',
 'amylase_max',
 'bilirubin_total_min',
 'bilirubin_total_max',
 'bilirubin_direct_min',
 'bilirubin_direct_max',
 'bilirubin_indirect_min',
 'bilirubin_indirect_max',
 'ck_cpk_min',
 'ck_cpk_max',
 'ck_mb_min',
 'ck_mb_max',
 'ggt_min',
 'ggt_max',
 'ld_ldh_min',
 'ld_ldh_max',
 'so2_min',
 'so2_max',
 'po2_min',
 'po2_max']

In [5]:
#making a demographic dataframe
df_demographic = df_cohort_step3[["subject_id", "stay_id"] + Demographics].copy()
df_demographic.head()

,subject_id,stay_id,insurance,language,race,marital_status,age,gender,first_careunit
0,10001217,37067082,Other,?,WHITE,MARRIED,55,F,Surgical Intensive Care Unit (SICU)
1,10001725,31205490,Other,ENGLISH,WHITE,MARRIED,46,F,Medical/Surgical Intensive Care Unit (MICU/SICU)
2,10001884,37510196,Medicare,ENGLISH,BLACK/AFRICAN AMERICAN,MARRIED,77,F,Medical Intensive Care Unit (MICU)
3,10002013,39060235,Medicare,ENGLISH,OTHER,SINGLE,57,F,Cardiac Vascular Intensive Care Unit (CVICU)
4,10002155,33685454,Other,ENGLISH,WHITE,MARRIED,81,F,Coronary Care Unit (CCU)

In [6]:
# making only for static dataframe

df_static_labs = df_cohort_step3[["stay_id"] + static_features].copy()

df_static_labs.head()

,stay_id,sofa2_respiration_24h_max,sofa2_cardiovascular_24h_max,sofa2_coagulation_24h_max,sofa2_liver_24h_max,sofa2_renal_24h_max,sofa2_cns_24h_max,heart_rate_min,heart_rate_max,heart_rate_mean,...,ck_mb_min,ck_mb_max,ggt_min,ggt_max,ld_ldh_min,ld_ldh_max,so2_min,so2_max,po2_min,po2_max
0,37067082,NaN,0.0,0.0,NaN,0.0,0.0,78.0,106.0,93.200000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,31205490,NaN,1.0,0.0,NaN,0.0,0.0,55.0,91.0,79.480000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,37510196,NaN,3.0,1.0,0.0,0.0,0.0,38.0,80.0,71.392857,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,49.0
3,39060235,3.0,1.0,0.0,NaN,0.0,0.0,80.0,105.0,94.636364,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.0,462.0
4,33685454,2.0,1.0,0.0,NaN,1.0,0.0,65.0,83.0,73.720000,...,15.1,18.2,NaN,NaN,507.0,507.0,NaN,NaN,76.0,76.0

In [7]:
#adding static suffix so we can distinguih them from time-series features later on
df_static_labs = df_static_labs.rename(columns={col: col + "_static" for col in static_features})

df_static_labs

,stay_id,sofa2_respiration_24h_max_static,sofa2_cardiovascular_24h_max_static,sofa2_coagulation_24h_max_static,sofa2_liver_24h_max_static,sofa2_renal_24h_max_static,sofa2_cns_24h_max_static,heart_rate_min_static,heart_rate_max_static,heart_rate_mean_static,...,ck_mb_min_static,ck_mb_max_static,ggt_min_static,ggt_max_static,ld_ldh_min_static,ld_ldh_max_static,so2_min_static,so2_max_static,po2_min_static,po2_max_static
0,37067082,NaN,0.0,0.0,NaN,0.0,0.0,78.0,106.0,93.200000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,31205490,NaN,1.0,0.0,NaN,0.0,0.0,55.0,91.0,79.480000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,37510196,NaN,3.0,1.0,0.0,0.0,0.0,38.0,80.0,71.392857,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,49.0
3,39060235,3.0,1.0,0.0,NaN,0.0,0.0,80.0,105.0,94.636364,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.0,462.0
4,33685454,2.0,1.0,0.0,NaN,1.0,0.0,65.0,83.0,73.720000,...,15.1,18.2,NaN,NaN,507.0,507.0,NaN,NaN,76.0,76.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40452,37364566,NaN,0.0,3.0,3.0,0.0,2.0,100.0,133.0,113.666667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40453,32336619,1.0,0.0,1.0,NaN,0.0,2.0,76.0,110.0,87.758621,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,131.0,209.0
40454,36075953,NaN,0.0,0.0,0.0,0.0,1.0,93.0,109.0,100.423077,...,NaN,NaN,NaN,NaN,238.0,238.0,NaN,NaN,35.0,36.0
40455,38978960,3.0,1.0,0.0,NaN,0.0,4.0,71.0,100.0,84.666667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61.0,212.0
40456,36195440,2.0,1.0,1.0,1.0,1.0,2.0,76.0,107.0,91.461538,...,10.2,11.2,NaN,NaN,100.0,100.0,NaN,NaN,114.0,114.0

In [9]:
#merge them according to stay_id
df_static_features = df_demographic.merge(df_static_labs, on="stay_id")

df_static_features

,subject_id,stay_id,insurance,language,race,marital_status,age,gender,first_careunit,sofa2_respiration_24h_max_static,...,ck_mb_min_static,ck_mb_max_static,ggt_min_static,ggt_max_static,ld_ldh_min_static,ld_ldh_max_static,so2_min_static,so2_max_static,po2_min_static,po2_max_static
0,10001217,37067082,Other,?,WHITE,MARRIED,55,F,Surgical Intensive Care Unit (SICU),NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10001725,31205490,Other,ENGLISH,WHITE,MARRIED,46,F,Medical/Surgical Intensive Care Unit (MICU/SICU),NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10001884,37510196,Medicare,ENGLISH,BLACK/AFRICAN AMERICAN,MARRIED,77,F,Medical Intensive Care Unit (MICU),NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,49.0
3,10002013,39060235,Medicare,ENGLISH,OTHER,SINGLE,57,F,Cardiac Vascular Intensive Care Unit (CVICU),3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.0,462.0
4,10002155,33685454,Other,ENGLISH,WHITE,MARRIED,81,F,Coronary Care Unit (CCU),2.0,...,15.1,18.2,NaN,NaN,507.0,507.0,NaN,NaN,76.0,76.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40452,19999297,37364566,Other,ENGLISH,MULTIPLE RACE/ETHNICITY,SINGLE,42,M,Medical Intensive Care Unit (MICU),NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40453,19999442,32336619,Medicaid,ENGLISH,WHITE,DIVORCED,43,M,Surgical Intensive Care Unit (SICU),1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,131.0,209.0
40454,19999828,36075953,Other,ENGLISH,WHITE,SINGLE,48,F,Medical Intensive Care Unit (MICU),NaN,...,NaN,NaN,NaN,NaN,238.0,238.0,NaN,NaN,35.0,36.0
40455,19999840,38978960,Other,ENGLISH,WHITE,WIDOWED,58,M,Trauma SICU (TSICU),3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61.0,212.0
40456,19999987,36195440,Other,ENGLISH,UNKNOWN,NaN,57,F,Trauma SICU (TSICU),2.0,...,10.2,11.2,NaN,NaN,100.0,100.0,NaN,NaN,114.0,114.0

In [10]:
#exporting the dataframe to csv for step 4
df_static_features.to_csv("cohort_step_3.csv", index=False)